Traceback (most recent call last):
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# list of lists
M = [[2, 3, 1, 4],
    [5, 1, 0, 3],
    [7, -2, 3, 5]]
M[0][0], M[1][0], M[1][2] # M[0] is the first list in M, M[0][0] is the first element in the first list
M[1,2]
# run this cell and notice the error message
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-9138b44a0512>[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m     [7, -2, 3, 5]]
[1;32m      5[0m [0mM[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mM[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mM[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m[[0m[0;36m2[0m[0;34m][0m [0;31m# M[0] is the first list in M, M[0][0] is the first element in the first list[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m [0mM[0m[0;34m[[0m[0;36m1[0m[0;34m,[0m[0;36m2[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0;31m# run this cell and notice the error message[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: list indices must be integers or slices, not tuple
TypeError: list indices must be integers or slices, not tuple

