Traceback (most recent call last):
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jeanwalrand/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
img = np.zeros((512,512,3),np.uint8) 
cv2.line(img,(0,0),(img.shape[1],\
                    img.shape[0]),(255,255,0),3)
cv2.rectangle(img,(0,0),(250,350),(0,0,255),2)
cv2.circle(img,(200,390),80,(0,255,0),5)
cv2.putText(img," OpenCV  ",(300,200),\
            cv2.FONT_HERSHEY_COMPLEX,1,(0,255,255),2)
plt.imshow(toRGB(img))
plt.title('Drawing in OpenCV')
plt.show()
display(button)  
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-4-978937eb27cd>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m cv2.putText(img," OpenCV  ",(300,200),\
[1;32m      7[0m             cv2.FONT_HERSHEY_COMPLEX,1,(0,255,255),2)
[0;32m----> 8[0;31m [0mplt[0m[0;34m.[0m[0mimshow[0m[0;34m([0m[0mtoRGB[0m[0;34m([0m[0mimg[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0mplt[0m[0;34m.[0m[0mtitle[0m[0;34m([0m[0;34m'Drawing in OpenCV'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0mplt[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'toRGB' is not defined
NameError: name 'toRGB' is not defined

